### ISSUE TITLE
如何使用gotoNoteByTrackIndex跳转到某个小节的开始呢？

### ISSUE THREAD

**Issue by starock** [Lugia123/XMIDI-2.0#1]
首先很感谢你提供的这个开源库！正需要这个。

现在我有个问题希望得到帮助。

一般情况下，跳转乐曲播放位置都是跳转小节，而不是某一个具体的音符位置(int值)。哦，当然，每小节的起始也是有一个索引数字的，但是我该如何得到它呢？

比如，我想通过方法来跳转到第二小节的起始处该如何实现？

我觉着扩展出一个计算小节并获取该小节起始位置索引数字的方法非常实用（比如，这样就可以很容易实现某个乐曲段落的循环播放）。

我的想法就是在解析MIDI文件内容的时候，累加每个音符的时值，当累加值==一小节应有的时值的时候，下一个index就是下一小节开始的位置。把这个位置添加到一个动态数组中。然后清空累加值，进行下一小节的计算，如此循环。最后，动态数组的长度+1就是该乐曲的小节总数，而且可以通过这个数组来获取乐曲每小节的起始位置了。

或者，你已经有了相应的实现方法，还请指点。

期待你的回复，谢谢！

**Comment by Lugia123** [comment]
这个实现起来有点复杂，需要将MIDI转换成曲谱数据，这样才能获取小节信息。
你需要MIDI转曲谱的API来实现所需要的功能。
十分抱歉帮不上你什么忙，目前我没有什么好方法来实现MIDI转曲谱的功能。
